import "./globals.css";

export const metadata = {
  title: "Nitesh Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="bg-zinc-700 w-screen h-screen">{children}</body>
    </html>
  );
}
